In [9]:
import pandas as pd
import numpy as np
import xarray as xr
import netCDF4 as nc4
%matplotlib inline
from matplotlib import pyplot as plt
import os #to get access to Windows OS

In [10]:
directory = 'C:/Users/18593/NDLAS A Primary/'
file = 'NLDAS_FORA0125_H.A20200308.0200.002.grb.SUB.nc4'

# use os.path.join to combine the parts
full_path = os.path.join(directory, file)

In [11]:
tornado_raw = pd.read_csv("https://raw.githubusercontent.com/RouseJo/DTSC691/main/tornados.csv")
tornado_raw

,om,yr,mo,dy,date,time,tz,datetime_utc,st,stf,...,elon,len,wid,ns,sn,f1,f2,f3,f4,fc
0,192,1950,10,1,1950-10-01,21:00:00,America/Chicago,1950-10-02T03:00:00Z,OK,40,...,-102.3000,15.80,10,1,1,25,0,0,0,False
1,193,1950,10,9,1950-10-09,02:15:00,America/Chicago,1950-10-09T08:15:00Z,NC,37,...,0.0000,2.00,880,1,1,47,0,0,0,False
2,195,1950,11,20,1950-11-20,02:20:00,America/Chicago,1950-11-20T08:20:00Z,KY,21,...,0.0000,0.10,10,1,1,177,0,0,0,False
3,196,1950,11,20,1950-11-20,04:00:00,America/Chicago,1950-11-20T10:00:00Z,KY,21,...,0.0000,0.10,10,1,1,209,0,0,0,False
4,197,1950,11,20,1950-11-20,07:30:00,America/Chicago,1950-11-20T13:30:00Z,MS,28,...,0.0000,2.00,37,1,1,101,0,0,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68688,621922,2022,9,28,2022-09-28,13:32:00,America/Chicago,2022-09-28T18:32:00Z,FL,12,...,-80.8841,3.00,100,1,1,9,0,0,0,False
68689,621923,2022,9,30,2022-09-30,10:25:00,America/Chicago,2022-09-30T15:25:00Z,NC,37,...,-78.3011,0.74,20,1,1,19,0,0,0,False
68690,621924,2022,9,30,2022-09-30,13:22:00,America/Chicago,2022-09-30T18:22:00Z,NC,37,...,-76.7147,0.70,12,1,1,13,0,0,0,False
68691,621900,2022,9,4,2022-09-04,15:44:00,America/Chicago,2022-09-04T20:44:00Z,OH,39,...,-80.6555,0.07,15,1,1,99,0,0,0,False
68692,621901,2022,9,9,2022-09-09,23:21:00,America/Chicago,2022-09-10T04:21:00Z,SC,45,...,-79.7537,0.68,125,1,1,19,0,0,0,False

In [12]:
dt = pd.to_datetime(tornado_raw['datetime_utc'])

nomin = dt.apply(lambda t: t.replace(minute=0)).astype(str)
nomin

0        1950-10-02 03:00:00+00:00
1        1950-10-09 08:00:00+00:00
2        1950-11-20 08:00:00+00:00
3        1950-11-20 10:00:00+00:00
4        1950-11-20 13:00:00+00:00
                   ...
68688    2022-09-28 18:00:00+00:00
68689    2022-09-30 15:00:00+00:00
68690    2022-09-30 18:00:00+00:00
68691    2022-09-04 20:00:00+00:00
68692    2022-09-10 04:00:00+00:00
Name: datetime_utc, Length: 68693, dtype: object

In [13]:
tornado_raw['hr'] = nomin
tornado_raw

,om,yr,mo,dy,date,time,tz,datetime_utc,st,stf,...,len,wid,ns,sn,f1,f2,f3,f4,fc,hr
0,192,1950,10,1,1950-10-01,21:00:00,America/Chicago,1950-10-02T03:00:00Z,OK,40,...,15.80,10,1,1,25,0,0,0,False,1950-10-02 03:00:00+00:00
1,193,1950,10,9,1950-10-09,02:15:00,America/Chicago,1950-10-09T08:15:00Z,NC,37,...,2.00,880,1,1,47,0,0,0,False,1950-10-09 08:00:00+00:00
2,195,1950,11,20,1950-11-20,02:20:00,America/Chicago,1950-11-20T08:20:00Z,KY,21,...,0.10,10,1,1,177,0,0,0,False,1950-11-20 08:00:00+00:00
3,196,1950,11,20,1950-11-20,04:00:00,America/Chicago,1950-11-20T10:00:00Z,KY,21,...,0.10,10,1,1,209,0,0,0,False,1950-11-20 10:00:00+00:00
4,197,1950,11,20,1950-11-20,07:30:00,America/Chicago,1950-11-20T13:30:00Z,MS,28,...,2.00,37,1,1,101,0,0,0,False,1950-11-20 13:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68688,621922,2022,9,28,2022-09-28,13:32:00,America/Chicago,2022-09-28T18:32:00Z,FL,12,...,3.00,100,1,1,9,0,0,0,False,2022-09-28 18:00:00+00:00
68689,621923,2022,9,30,2022-09-30,10:25:00,America/Chicago,2022-09-30T15:25:00Z,NC,37,...,0.74,20,1,1,19,0,0,0,False,2022-09-30 15:00:00+00:00
68690,621924,2022,9,30,2022-09-30,13:22:00,America/Chicago,2022-09-30T18:22:00Z,NC,37,...,0.70,12,1,1,13,0,0,0,False,2022-09-30 18:00:00+00:00
68691,621900,2022,9,4,2022-09-04,15:44:00,America/Chicago,2022-09-04T20:44:00Z,OH,39,...,0.07,15,1,1,99,0,0,0,False,2022-09-04 20:00:00+00:00
68692,621901,2022,9,9,2022-09-09,23:21:00,America/Chicago,2022-09-10T04:21:00Z,SC,45,...,0.68,125,1,1,19,0,0,0,False,2022-09-10 04:00:00+00:00

This is a selection of data between January 1st 2010 and December 31st 2020. New rating scales were used beginning in2007.

In [65]:
tornado_decade = tornado_raw[(tornado_raw['yr'] > 2009) & (tornado_raw['yr'] < 2021)]
tornado_decade

,om,yr,mo,dy,date,time,tz,datetime_utc,st,stf,...,len,wid,ns,sn,f1,f2,f3,f4,fc,hr
53228,1101,2010,10,18,2010-10-18,17:43:00,America/Chicago,2010-10-18T22:43:00Z,AZ,4,...,1.23,25,1,1,15,0,0,0,False,2010-10-18 22:00:00+00:00
53229,1102,2010,10,21,2010-10-21,16:48:00,America/Chicago,2010-10-21T21:48:00Z,TX,48,...,0.78,75,1,1,461,0,0,0,False,2010-10-21 21:00:00+00:00
53230,1103,2010,10,21,2010-10-21,17:34:00,America/Chicago,2010-10-21T22:34:00Z,AZ,4,...,0.81,20,1,1,1,0,0,0,False,2010-10-21 22:00:00+00:00
53231,1104,2010,10,21,2010-10-21,17:47:00,America/Chicago,2010-10-21T22:47:00Z,NM,35,...,2.86,200,1,1,5,0,0,0,False,2010-10-21 22:00:00+00:00
53232,1105,2010,10,21,2010-10-21,18:03:00,America/Chicago,2010-10-21T23:03:00Z,NM,35,...,0.56,50,1,1,5,0,0,0,False,2010-10-21 23:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66231,619522,2020,9,1,2020-09-01,18:10:00,America/Chicago,2020-09-01T23:10:00Z,TX,48,...,0.01,30,1,1,191,0,0,0,False,2020-09-01 23:00:00+00:00
66232,619523,2020,9,3,2020-09-03,15:57:00,America/Chicago,2020-09-03T20:57:00Z,MD,24,...,6.05,100,1,1,3,0,0,0,False,2020-09-03 20:00:00+00:00
66233,619524,2020,9,5,2020-09-05,16:17:00,America/Chicago,2020-09-05T21:17:00Z,CA,6,...,12.02,50,1,1,39,0,0,0,False,2020-09-05 21:00:00+00:00
66234,619525,2020,9,5,2020-09-05,18:29:00,America/Chicago,2020-09-05T23:29:00Z,CA,6,...,1.12,25,1,1,19,0,0,0,False,2020-09-05 23:00:00+00:00
66235,619526,2020,9,7,2020-09-07,15:14:00,America/Chicago,2020-09-07T20:14:00Z,OH,39,...,3.21,150,1,1,41,0,0,0,False,2020-09-07 20:00:00+00:00

In [66]:
tornado_decade['hrcode'] = tornado_decade.hr.str.replace('-','')
tornado_decade

C:\Users\18593\AppData\Local\Temp\ipykernel_25860\744176456.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tornado_decade['hrcode'] = tornado_decade.hr.str.replace('-','')

,om,yr,mo,dy,date,time,tz,datetime_utc,st,stf,...,wid,ns,sn,f1,f2,f3,f4,fc,hr,hrcode
53228,1101,2010,10,18,2010-10-18,17:43:00,America/Chicago,2010-10-18T22:43:00Z,AZ,4,...,25,1,1,15,0,0,0,False,2010-10-18 22:00:00+00:00,20101018 22:00:00+00:00
53229,1102,2010,10,21,2010-10-21,16:48:00,America/Chicago,2010-10-21T21:48:00Z,TX,48,...,75,1,1,461,0,0,0,False,2010-10-21 21:00:00+00:00,20101021 21:00:00+00:00
53230,1103,2010,10,21,2010-10-21,17:34:00,America/Chicago,2010-10-21T22:34:00Z,AZ,4,...,20,1,1,1,0,0,0,False,2010-10-21 22:00:00+00:00,20101021 22:00:00+00:00
53231,1104,2010,10,21,2010-10-21,17:47:00,America/Chicago,2010-10-21T22:47:00Z,NM,35,...,200,1,1,5,0,0,0,False,2010-10-21 22:00:00+00:00,20101021 22:00:00+00:00
53232,1105,2010,10,21,2010-10-21,18:03:00,America/Chicago,2010-10-21T23:03:00Z,NM,35,...,50,1,1,5,0,0,0,False,2010-10-21 23:00:00+00:00,20101021 23:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66231,619522,2020,9,1,2020-09-01,18:10:00,America/Chicago,2020-09-01T23:10:00Z,TX,48,...,30,1,1,191,0,0,0,False,2020-09-01 23:00:00+00:00,20200901 23:00:00+00:00
66232,619523,2020,9,3,2020-09-03,15:57:00,America/Chicago,2020-09-03T20:57:00Z,MD,24,...,100,1,1,3,0,0,0,False,2020-09-03 20:00:00+00:00,20200903 20:00:00+00:00
66233,619524,2020,9,5,2020-09-05,16:17:00,America/Chicago,2020-09-05T21:17:00Z,CA,6,...,50,1,1,39,0,0,0,False,2020-09-05 21:00:00+00:00,20200905 21:00:00+00:00
66234,619525,2020,9,5,2020-09-05,18:29:00,America/Chicago,2020-09-05T23:29:00Z,CA,6,...,25,1,1,19,0,0,0,False,2020-09-05 23:00:00+00:00,20200905 23:00:00+00:00
66235,619526,2020,9,7,2020-09-07,15:14:00,America/Chicago,2020-09-07T20:14:00Z,OH,39,...,150,1,1,41,0,0,0,False,2020-09-07 20:00:00+00:00,20200907 20:00:00+00:00

In [67]:
tornado_decade['code'] =  tornado_decade['hrcode'].astype(str).str[:8] + '.' + tornado_decade['hrcode'].astype(str).str[9:11]

tornado_decade

C:\Users\18593\AppData\Local\Temp\ipykernel_25860\1612356847.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tornado_decade['code'] =  tornado_decade['hrcode'].astype(str).str[:8] + '.' + tornado_decade['hrcode'].astype(str).str[9:11]

,om,yr,mo,dy,date,time,tz,datetime_utc,st,stf,...,ns,sn,f1,f2,f3,f4,fc,hr,hrcode,code
53228,1101,2010,10,18,2010-10-18,17:43:00,America/Chicago,2010-10-18T22:43:00Z,AZ,4,...,1,1,15,0,0,0,False,2010-10-18 22:00:00+00:00,20101018 22:00:00+00:00,20101018.22
53229,1102,2010,10,21,2010-10-21,16:48:00,America/Chicago,2010-10-21T21:48:00Z,TX,48,...,1,1,461,0,0,0,False,2010-10-21 21:00:00+00:00,20101021 21:00:00+00:00,20101021.21
53230,1103,2010,10,21,2010-10-21,17:34:00,America/Chicago,2010-10-21T22:34:00Z,AZ,4,...,1,1,1,0,0,0,False,2010-10-21 22:00:00+00:00,20101021 22:00:00+00:00,20101021.22
53231,1104,2010,10,21,2010-10-21,17:47:00,America/Chicago,2010-10-21T22:47:00Z,NM,35,...,1,1,5,0,0,0,False,2010-10-21 22:00:00+00:00,20101021 22:00:00+00:00,20101021.22
53232,1105,2010,10,21,2010-10-21,18:03:00,America/Chicago,2010-10-21T23:03:00Z,NM,35,...,1,1,5,0,0,0,False,2010-10-21 23:00:00+00:00,20101021 23:00:00+00:00,20101021.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66231,619522,2020,9,1,2020-09-01,18:10:00,America/Chicago,2020-09-01T23:10:00Z,TX,48,...,1,1,191,0,0,0,False,2020-09-01 23:00:00+00:00,20200901 23:00:00+00:00,20200901.23
66232,619523,2020,9,3,2020-09-03,15:57:00,America/Chicago,2020-09-03T20:57:00Z,MD,24,...,1,1,3,0,0,0,False,2020-09-03 20:00:00+00:00,20200903 20:00:00+00:00,20200903.20
66233,619524,2020,9,5,2020-09-05,16:17:00,America/Chicago,2020-09-05T21:17:00Z,CA,6,...,1,1,39,0,0,0,False,2020-09-05 21:00:00+00:00,20200905 21:00:00+00:00,20200905.21
66234,619525,2020,9,5,2020-09-05,18:29:00,America/Chicago,2020-09-05T23:29:00Z,CA,6,...,1,1,19,0,0,0,False,2020-09-05 23:00:00+00:00,20200905 23:00:00+00:00,20200905.23
66235,619526,2020,9,7,2020-09-07,15:14:00,America/Chicago,2020-09-07T20:14:00Z,OH,39,...,1,1,41,0,0,0,False,2020-09-07 20:00:00+00:00,20200907 20:00:00+00:00,20200907.20

In [68]:
head = tornado_decade.head()
head

,om,yr,mo,dy,date,time,tz,datetime_utc,st,stf,...,ns,sn,f1,f2,f3,f4,fc,hr,hrcode,code
53228,1101,2010,10,18,2010-10-18,17:43:00,America/Chicago,2010-10-18T22:43:00Z,AZ,4,...,1,1,15,0,0,0,False,2010-10-18 22:00:00+00:00,20101018 22:00:00+00:00,20101018.22
53229,1102,2010,10,21,2010-10-21,16:48:00,America/Chicago,2010-10-21T21:48:00Z,TX,48,...,1,1,461,0,0,0,False,2010-10-21 21:00:00+00:00,20101021 21:00:00+00:00,20101021.21
53230,1103,2010,10,21,2010-10-21,17:34:00,America/Chicago,2010-10-21T22:34:00Z,AZ,4,...,1,1,1,0,0,0,False,2010-10-21 22:00:00+00:00,20101021 22:00:00+00:00,20101021.22
53231,1104,2010,10,21,2010-10-21,17:47:00,America/Chicago,2010-10-21T22:47:00Z,NM,35,...,1,1,5,0,0,0,False,2010-10-21 22:00:00+00:00,20101021 22:00:00+00:00,20101021.22
53232,1105,2010,10,21,2010-10-21,18:03:00,America/Chicago,2010-10-21T23:03:00Z,NM,35,...,1,1,5,0,0,0,False,2010-10-21 23:00:00+00:00,20101021 23:00:00+00:00,20101021.23

In [69]:
dir_list = os.listdir(directory)

my_list = []
for dtg in tornado_decade['code']:
    for file_name in dir_list:
        if dtg in file_name:
            my_list.append(file_name)
            #print(file_name)
            break
    else:
        #print('na')
        my_list.append('None')

my_list

['None',
 'NLDAS_FORA0125_H.A20101021.2100.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101021.2300.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101024.1900.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101024.2100.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101024.2300.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101025.0400.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101025.0700.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101025.0700.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101025.0900.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101025.0900.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101026.0900.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101026.1100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1100.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101026.1300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1300.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101026.1500.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1500.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1500.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1600.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1600.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1600.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101026.1800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.1800.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101026.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.2100.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101026.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101026.2300.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101027.0200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101027.0200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101027.0200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101027.0300.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101027.0600.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101027.1900.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101027.2000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101027.2000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101027.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101027.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101027.2200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101028.0300.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101006.1100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101006.1200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101006.1500.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101006.1800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101006.1800.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101007.2200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101007.2200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101117.0600.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101117.0700.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101122.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101122.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101122.2200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101122.2200.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101123.1700.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101125.0100.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101126.0400.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101126.0500.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101126.0500.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101126.0500.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101126.0500.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101126.0500.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101129.2100.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101130.0100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101130.0100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101130.0100.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101130.0300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101130.0300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101130.0300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101130.0500.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101130.0500.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101130.0500.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101130.0600.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101130.0600.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101130.0800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101130.0800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101130.1000.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101130.1300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101130.1300.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101130.2000.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101201.0000.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101103.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101103.2100.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101231.0500.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101231.0500.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101231.1200.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101231.1400.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101231.1600.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101231.1600.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101231.1600.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101231.1800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101231.1800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101231.1800.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101231.2000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20101231.2000.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20101231.2300.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20101201.1400.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100311.0000.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100311.0300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100311.0300.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100311.0500.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100311.1900.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100312.2100.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100325.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100325.2300.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100328.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100328.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100328.2200.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100329.0200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100329.0200.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100329.1100.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100309.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100309.0000.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100417.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100420.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100420.2300.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100422.1800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.1800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.1800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.1800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.1800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.1900.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.1900.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.1900.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.1900.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.1900.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.1900.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100422.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.2100.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100422.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100422.2300.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100423.1600.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100423.2200.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100424.0000.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100424.0600.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100424.0600.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100424.1200.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100424.1400.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100424.1600.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100424.1600.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100424.1800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100424.1800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100424.1800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100424.1800.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100424.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100424.2200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100424.2200.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100425.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100425.0000.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100425.0300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100425.0400.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100425.0400.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100425.0600.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100425.2300.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100429.2300.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100430.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100430.2100.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100430.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100430.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100430.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100430.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100430.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100430.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100430.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100430.2300.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100501.0100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100501.0100.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100405.2000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100407.2000.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100408.1100.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100408.1700.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100409.0200.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100510.1800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100510.1800.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100510.2000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100510.2000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100510.2000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100510.2000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100510.2000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100510.2000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100510.2000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100510.2000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100510.2000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100510.2000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100510.2000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100510.2000.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100510.2200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100510.2200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100510.2200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100510.2200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100510.2200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100510.2200.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100511.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100511.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100511.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100511.0000.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100512.0000.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100512.1900.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100512.1900.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100512.2200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100513.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100513.0000.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100513.0800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100513.0800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100513.0800.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100513.0800.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100513.1000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100513.1000.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100513.1200.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100514.1600.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100514.1800.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100515.1100.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100516.1500.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100516.2200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100517.0100.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100517.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100518.1200.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100518.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100518.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100518.2100.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100518.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100518.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100518.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100518.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100518.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100518.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100518.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100518.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100518.2300.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100519.0100.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100519.0300.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100519.0500.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100519.0500.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100519.0700.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100519.0700.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100519.2000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100519.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100519.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100519.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100519.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100519.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100519.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100519.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100519.2200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100519.2200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100519.2200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100519.2200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100519.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100519.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100519.2300.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100520.0100.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100520.1900.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100520.2200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100520.2200.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100521.1600.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100521.1600.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100521.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100521.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100522.2100.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100522.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100522.2300.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100522.2300.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100523.0100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100523.0100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100523.0100.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100524.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100524.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100524.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100524.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100524.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100524.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100524.0000.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100524.1700.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100524.1700.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100524.1700.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100524.1900.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100524.1900.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100524.1900.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100524.1900.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100524.1900.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100524.1900.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100524.2000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100524.2200.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100525.0100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100525.1500.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100525.1800.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100525.2100.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100525.2100.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100526.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100526.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100526.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100526.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100526.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100526.0000.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100526.0000.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100526.0200.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100526.0200.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100526.2000.002.grb.SUB.nc4',
 'None',
 'NLDAS_FORA0125_H.A20100526.2200.002.grb.SUB.nc4',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100531.2000.002.grb.SUB.nc4',
 'None',
 'None',
 'None',
 'None',
 'NLDAS_FORA0125_H.A20100501.1700.002.grb.SUB.nc4',
 'NLDAS_FORA0125_H.A20100501.2000.002.grb.SUB.nc4',
 'None',

In [70]:
tornado_decade['fn'] = my_list
tornado_decade

C:\Users\18593\AppData\Local\Temp\ipykernel_25860\910713039.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tornado_decade['fn'] = my_list

,om,yr,mo,dy,date,time,tz,datetime_utc,st,stf,...,sn,f1,f2,f3,f4,fc,hr,hrcode,code,fn
53228,1101,2010,10,18,2010-10-18,17:43:00,America/Chicago,2010-10-18T22:43:00Z,AZ,4,...,1,15,0,0,0,False,2010-10-18 22:00:00+00:00,20101018 22:00:00+00:00,20101018.22,None
53229,1102,2010,10,21,2010-10-21,16:48:00,America/Chicago,2010-10-21T21:48:00Z,TX,48,...,1,461,0,0,0,False,2010-10-21 21:00:00+00:00,20101021 21:00:00+00:00,20101021.21,NLDAS_FORA0125_H.A20101021.2100.002.grb.SUB.nc4
53230,1103,2010,10,21,2010-10-21,17:34:00,America/Chicago,2010-10-21T22:34:00Z,AZ,4,...,1,1,0,0,0,False,2010-10-21 22:00:00+00:00,20101021 22:00:00+00:00,20101021.22,None
53231,1104,2010,10,21,2010-10-21,17:47:00,America/Chicago,2010-10-21T22:47:00Z,NM,35,...,1,5,0,0,0,False,2010-10-21 22:00:00+00:00,20101021 22:00:00+00:00,20101021.22,None
53232,1105,2010,10,21,2010-10-21,18:03:00,America/Chicago,2010-10-21T23:03:00Z,NM,35,...,1,5,0,0,0,False,2010-10-21 23:00:00+00:00,20101021 23:00:00+00:00,20101021.23,NLDAS_FORA0125_H.A20101021.2300.002.grb.SUB.nc4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66231,619522,2020,9,1,2020-09-01,18:10:00,America/Chicago,2020-09-01T23:10:00Z,TX,48,...,1,191,0,0,0,False,2020-09-01 23:00:00+00:00,20200901 23:00:00+00:00,20200901.23,NLDAS_FORA0125_H.A20200901.2300.002.grb.SUB.nc4
66232,619523,2020,9,3,2020-09-03,15:57:00,America/Chicago,2020-09-03T20:57:00Z,MD,24,...,1,3,0,0,0,False,2020-09-03 20:00:00+00:00,20200903 20:00:00+00:00,20200903.20,None
66233,619524,2020,9,5,2020-09-05,16:17:00,America/Chicago,2020-09-05T21:17:00Z,CA,6,...,1,39,0,0,0,False,2020-09-05 21:00:00+00:00,20200905 21:00:00+00:00,20200905.21,None
66234,619525,2020,9,5,2020-09-05,18:29:00,America/Chicago,2020-09-05T23:29:00Z,CA,6,...,1,19,0,0,0,False,2020-09-05 23:00:00+00:00,20200905 23:00:00+00:00,20200905.23,NLDAS_FORA0125_H.A20200905.2300.002.grb.SUB.nc4
66235,619526,2020,9,7,2020-09-07,15:14:00,America/Chicago,2020-09-07T20:14:00Z,OH,39,...,1,41,0,0,0,False,2020-09-07 20:00:00+00:00,20200907 20:00:00+00:00,20200907.20,None

In [71]:
filtered = tornado_decade.loc[tornado_decade['fn'] != 'None']
filtered

,om,yr,mo,dy,date,time,tz,datetime_utc,st,stf,...,sn,f1,f2,f3,f4,fc,hr,hrcode,code,fn
53229,1102,2010,10,21,2010-10-21,16:48:00,America/Chicago,2010-10-21T21:48:00Z,TX,48,...,1,461,0,0,0,False,2010-10-21 21:00:00+00:00,20101021 21:00:00+00:00,20101021.21,NLDAS_FORA0125_H.A20101021.2100.002.grb.SUB.nc4
53232,1105,2010,10,21,2010-10-21,18:03:00,America/Chicago,2010-10-21T23:03:00Z,NM,35,...,1,5,0,0,0,False,2010-10-21 23:00:00+00:00,20101021 23:00:00+00:00,20101021.23,NLDAS_FORA0125_H.A20101021.2300.002.grb.SUB.nc4
53234,1107,2010,10,24,2010-10-24,14:30:00,America/Chicago,2010-10-24T19:30:00Z,TX,48,...,1,343,67,0,0,False,2010-10-24 19:00:00+00:00,20101024 19:00:00+00:00,20101024.19,NLDAS_FORA0125_H.A20101024.1900.002.grb.SUB.nc4
53236,1109,2010,10,24,2010-10-24,16:43:00,America/Chicago,2010-10-24T21:43:00Z,TX,48,...,1,349,0,0,0,False,2010-10-24 21:00:00+00:00,20101024 21:00:00+00:00,20101024.21,NLDAS_FORA0125_H.A20101024.2100.002.grb.SUB.nc4
53241,1114,2010,10,24,2010-10-24,18:20:00,America/Chicago,2010-10-24T23:20:00Z,OR,41,...,1,15,0,0,0,False,2010-10-24 23:00:00+00:00,20101024 23:00:00+00:00,20101024.23,NLDAS_FORA0125_H.A20101024.2300.002.grb.SUB.nc4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66226,619517,2020,9,1,2020-09-01,13:13:00,America/Chicago,2020-09-01T18:13:00Z,AR,5,...,1,45,0,0,0,False,2020-09-01 18:00:00+00:00,20200901 18:00:00+00:00,20200901.18,NLDAS_FORA0125_H.A20200901.1800.002.grb.SUB.nc4
66228,619519,2020,9,1,2020-09-01,15:14:00,America/Chicago,2020-09-01T20:14:00Z,MO,29,...,1,155,0,0,0,False,2020-09-01 20:00:00+00:00,20200901 20:00:00+00:00,20200901.20,NLDAS_FORA0125_H.A20200901.2000.002.grb.SUB.nc4
66229,619520,2020,9,1,2020-09-01,15:28:00,America/Chicago,2020-09-01T20:28:00Z,TN,47,...,1,187,0,0,0,False,2020-09-01 20:00:00+00:00,20200901 20:00:00+00:00,20200901.20,NLDAS_FORA0125_H.A20200901.2000.002.grb.SUB.nc4
66231,619522,2020,9,1,2020-09-01,18:10:00,America/Chicago,2020-09-01T23:10:00Z,TX,48,...,1,191,0,0,0,False,2020-09-01 23:00:00+00:00,20200901 23:00:00+00:00,20200901.23,NLDAS_FORA0125_H.A20200901.2300.002.grb.SUB.nc4
66234,619525,2020,9,5,2020-09-05,18:29:00,America/Chicago,2020-09-05T23:29:00Z,CA,6,...,1,19,0,0,0,False,2020-09-05 23:00:00+00:00,20200905 23:00:00+00:00,20200905.23,NLDAS_FORA0125_H.A20200905.2300.002.grb.SUB.nc4

In [73]:
df = pd.DataFrame(columns=["TMP", "SPFH", "PRES", "UGRD", "VGRD", "DLWRF", "CONVfrac", "CAPE", "PEVAP", "APCP", "DSWRF"]) 

for i in filtered['fn']:
    if i != 'none':
        sel_file = i
        j = filtered['slat'].iloc[0]
        k = filtered['slon'].iloc[0]
        sel_path = os.path.join(directory, sel_file)
        read_it = xr.open_dataset(sel_path, engine='netcdf4')
        isolate_it = read_it.sel(lat=j, lon=k, method='nearest').to_dataframe()
        features = isolate_it[["TMP", "SPFH", "PRES", "UGRD", "VGRD", "DLWRF", "CONVfrac", "CAPE", "PEVAP", "APCP", "DSWRF"]]
        feat_drop = features.reset_index(drop=True)
        #df = df.append(merge)
        df = pd.concat([feat_drop, df], ignore_index=True)
df

,TMP,SPFH,PRES,UGRD,VGRD,DLWRF,CONVfrac,CAPE,PEVAP,APCP,DSWRF
0,305.030029,0.011053,92842.328125,-4.21,3.52,425.940002,0.0,504.320007,0.7305,0.0000,335.984009
1,307.690002,0.010254,91664.898438,3.01,3.72,454.709991,0.0,118.592003,0.5762,0.0000,191.770004
2,307.380005,0.010856,91792.578125,5.05,3.60,450.190002,0.0,42.560001,0.8650,0.0000,529.296997
3,307.380005,0.010856,91792.578125,5.05,3.60,450.190002,0.0,42.560001,0.8650,0.0000,529.296997
4,306.929993,0.011528,91803.921875,6.25,4.31,450.190002,0.0,59.520000,0.7430,0.0000,528.392029
...,...,...,...,...,...,...,...,...,...,...,...
5457,298.410004,0.004245,91832.906250,4.53,0.90,323.250000,0.0,0.000000,0.5314,0.0000,204.259003
5458,300.950012,0.004091,91895.921875,6.47,1.22,323.250000,0.0,0.000000,0.8569,0.0000,541.406982
5459,299.690002,0.004552,92028.539062,6.75,1.20,327.739990,0.0,0.000000,0.8569,0.0000,687.705994
5460,301.779999,0.011449,91760.906250,-1.95,7.62,387.410004,1.0,2029.083008,0.5260,3.2663,207.296997
5461,303.190002,0.011703,91809.070312,-2.07,7.96,387.410004,0.0,2176.597900,0.8112,0.0000,533.333008

In [74]:
merge = pd.concat([filtered.reset_index(drop=True), df.reset_index(drop=True)], axis=1) 
#merge = pd.concat([no_none, df], axis = 1)
merge

,om,yr,mo,dy,date,time,tz,datetime_utc,st,stf,...,SPFH,PRES,UGRD,VGRD,DLWRF,CONVfrac,CAPE,PEVAP,APCP,DSWRF
0,1102,2010,10,21,2010-10-21,16:48:00,America/Chicago,2010-10-21T21:48:00Z,TX,48,...,0.011053,92842.328125,-4.21,3.52,425.940002,0.0,504.320007,0.7305,0.0000,335.984009
1,1105,2010,10,21,2010-10-21,18:03:00,America/Chicago,2010-10-21T23:03:00Z,NM,35,...,0.010254,91664.898438,3.01,3.72,454.709991,0.0,118.592003,0.5762,0.0000,191.770004
2,1107,2010,10,24,2010-10-24,14:30:00,America/Chicago,2010-10-24T19:30:00Z,TX,48,...,0.010856,91792.578125,5.05,3.60,450.190002,0.0,42.560001,0.8650,0.0000,529.296997
3,1109,2010,10,24,2010-10-24,16:43:00,America/Chicago,2010-10-24T21:43:00Z,TX,48,...,0.010856,91792.578125,5.05,3.60,450.190002,0.0,42.560001,0.8650,0.0000,529.296997
4,1114,2010,10,24,2010-10-24,18:20:00,America/Chicago,2010-10-24T23:20:00Z,OR,41,...,0.011528,91803.921875,6.25,4.31,450.190002,0.0,59.520000,0.7430,0.0000,528.392029
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5457,619517,2020,9,1,2020-09-01,13:13:00,America/Chicago,2020-09-01T18:13:00Z,AR,5,...,0.004245,91832.906250,4.53,0.90,323.250000,0.0,0.000000,0.5314,0.0000,204.259003
5458,619519,2020,9,1,2020-09-01,15:14:00,America/Chicago,2020-09-01T20:14:00Z,MO,29,...,0.004091,91895.921875,6.47,1.22,323.250000,0.0,0.000000,0.8569,0.0000,541.406982
5459,619520,2020,9,1,2020-09-01,15:28:00,America/Chicago,2020-09-01T20:28:00Z,TN,47,...,0.004552,92028.539062,6.75,1.20,327.739990,0.0,0.000000,0.8569,0.0000,687.705994
5460,619522,2020,9,1,2020-09-01,18:10:00,America/Chicago,2020-09-01T23:10:00Z,TX,48,...,0.011449,91760.906250,-1.95,7.62,387.410004,1.0,2029.083008,0.5260,3.2663,207.296997
5461,619525,2020,9,5,2020-09-05,18:29:00,America/Chicago,2020-09-05T23:29:00Z,CA,6,...,0.011703,91809.070312,-2.07,7.96,387.410004,0.0,2176.597900,0.8112,0.0000,533.333008

In [84]:
export = merge.to_csv('C:/Users/18593/NDLAS A Primary/Cleaned.csv', index = False)
export